### ISSUE TITLE
It's not possible to deselect an already selected project

### ISSUE THREAD

**Issue by AD7six** [cauditor/issues#4]
It just prompts a popup with "Failed to link project etc."

![screenshot from 2016-04-18 10-39-57](https://cloud.githubusercontent.com/assets/33387/14598336/f44cf3f0-0551-11e6-956a-830374a3b6c4.png)

Also looks like it's not possible to select repos of the same name (the originall and a fork).

And yes alerts are an extremely poor way to notify users of errors :)

**Comment by matthiasmullie** [comment]
Should be fixed now. Apparently, having permissions to create a hook doesn't also mean you can delete it - that needs elevated permissions. I had missed that.
If you log out & log in again, you should now be asked to grant Cauditor the new permissions, and that'll allow unlinking repos.

The alert has also been addressed :)

TODO: look into analyzing forks: it should be possible to have both, but looks like I need to doublecheck that.

**Comment by matthiasmullie** [comment]
I just tried importing an original & a fork and it seems to work. Any chance you could try that again?
