### ISSUE TITLE
There is no obvious link/instructions to report bugs

### ISSUE THREAD

**Issue by AD7six** [cauditor/issues#5]
The Beta badge links here - but I only knew that by looking at the page source, it is not the most obvious/appropriate place to put a link for reporting application bugs. I had expected "Feedback" or the email link to work for reporting application errors.

**Comment by matthiasmullie** [comment]
Hey @AD7six,

Yeah, it's not at all obvious that that beta label does anything.
I've just added a link in the footer. Do you think this is more discoverable?
